version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    ports:
      - "8080:80" # Acesse em http://localhost:8080
    volumes:
      - ./:/var/www/html # Hot‑reload do seu código
    environment:
      - DB_HOST=db
      - DB_DATABASE=movies_db
      - DB_USER=user
      - DB_PASSWORD=userpass
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"

volumes:
  db_data:
